/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher */

#ifndef _Included_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
#define _Included_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
 * Method:    configureNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher_configureNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher_closeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
 * Method:    startNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher_startNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
 * Method:    stopNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher_stopNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher
 * Method:    crushNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_bitcrusher_OpenSlBitCrusher_crushNative
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
