/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_noisepages_nettoyeur_openslstreamsample_Lowpass */

#ifndef _Included_com_noisepages_nettoyeur_openslstreamsample_Lowpass
#define _Included_com_noisepages_nettoyeur_openslstreamsample_Lowpass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noisepages_nettoyeur_openslstreamsample_Lowpass
 * Method:    configure
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_noisepages_nettoyeur_openslstreamsample_Lowpass_configure
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_noisepages_nettoyeur_openslstreamsample_Lowpass
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_openslstreamsample_Lowpass_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_openslstreamsample_Lowpass
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_noisepages_nettoyeur_openslstreamsample_Lowpass_start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_openslstreamsample_Lowpass
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_openslstreamsample_Lowpass_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_noisepages_nettoyeur_openslstreamsample_Lowpass
 * Method:    setAlpha
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_noisepages_nettoyeur_openslstreamsample_Lowpass_setAlpha
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
